In [ ]:
# No Need of GPU in Google Colab

In [1]:
!pip install --q --upgrade torch
!pip install --q --upgrade transformers
!pip install --q --upgrade huggingface_hub

In [20]:
import os
import torch
import transformers
from transformers import AutoTokenizer, AutoModelForCausalLM

In [3]:
from google.colab import userdata
HF_TOKEN = userdata.get('HF_TOKEN')
os.environ["HUGGINGFACE_TOKEN"] = HF_TOKEN

# !huggingface-cli login

# from huggingface_hub import login
# login()

In [13]:
model_id = "openai-community/gpt2-medium"

pipeline = transformers.pipeline(
    "text-generation",
    model=model_id,
    model_kwargs={"torch_dtype": torch.bfloat16},
    device_map="auto"
)

config.json:   0%|          | 0.00/718 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.52G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Device set to use cpu


In [ ]:
generated_text = pipeline("what is Openai.")
print(generated_text)

# Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
# [{'generated_text':
#   'what is Openai.io?\n\n
#   "Openai.io is a digital insurance broker that offers digital insurance products and services, with an emphasis on blockchain technology.
#   We bring experience in digital insurance and blockchain from our previous companies, and focus on'
# }]

In [ ]:
# from transformers import AutoTokenizer, AutoModelForCausalLM

# model_name = "openai-community/gpt2-medium"
# tokenizer = AutoTokenizer.from_pretrained(model_name)
# model = AutoModelForCausalLM.from_pretrained(model_name)

# prompt = "what is neural network"
# inputs = tokenizer(prompt, return_tensors="pt")
# outputs = model.generate(**inputs, max_length=1000)
# generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)

# print(generated_text)

# ======================================================
# Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
# what is neural network?

# Neural network is a computer program that can learn from data.
# It is a computer program that can learn from data.
# It is a computer program that can learn from data.
# It is a computer program that can learn from data.
# ...................
# It is a computer program that can learn from data.
# It is a computer program that can learn from data.
# It

In [ ]:
# print(prompt)
# what is neural network

In [ ]:
# print(inputs)
# {'input_ids': tensor([[10919,   318, 17019,  3127]]), 'attention_mask': tensor([[1, 1, 1, 1]])}

In [ ]:
# print(inputs[0])
# Encoding(num_tokens=4, attributes=[ids, type_ids, tokens, offsets, attention_mask, special_tokens_mask, overflowing])

In [ ]:
# print(outputs)

# tensor([[10919,   318, 17019,  3127,    30,   198,   198,  8199,  1523,  3127,
#            318,   257,  3644,  1430,   326,   460,  2193,   422,  1366,    13,
#            632,   318,   257,  3644,  1430,   326,   460,  2193,   422,  1366,
#             13,   632,   318,   257,  3644,  1430,   326,   460,  2193,   422,
#           3644,  1430,   326,   460,  2193,   422,  1366,    13,   632,   318,
#            257,  3644,  1430,   326,   460,  2193,   422,  1366,    13,   632]])

In [ ]:
# print(outputs[0])

# tensor([10919,   318, 17019,  3127,    30,   198,   198,  8199,  1523,  3127,
#            318,   257,  3644,  1430,   326,   460,  2193,   422,  1366,    13,
#            632,   318,   257,  3644,  1430,   326,   460,  2193,   422,  1366,
#             13,   632,   318,   257,  3644,  1430,   326,   460,  2193,   422,
#           3644,  1430,   326,   460,  2193,   422,  1366,    13,   632,   318,
#            257,  3644,  1430,   326,   460,  2193,   422,  1366,    13,   632])

In [ ]:
# print(outputs[0][0])
# tensor(10919)

In [ ]:
# print(len(outputs))
# print(len(outputs[0]))
# 1
# 1000

In [ ]:
# for i in range(len(outputs[0])):
#     generated_text_2 = tokenizer.decode(outputs[0][i])
#     print(generated_text_2, end='')

# what is neural network?

# Neural network is a computer program that can learn from data.
# It is a computer program that can learn from data.
# It is a computer program that can learn from data.
# It

In [ ]:
# for i in range(len(outputs[0])):
#     generated_text_2 = tokenizer.decode(outputs[0][i],skip_special_tokens=True)
#     print(generated_text_2, end='')

# # what is neural network?

# # Neural network is a computer program that can learn from data.
# # It is a computer program that can learn from data.
# # It is a computer program that can learn from data.
# # It

In [ ]:
# prompt = "what is the capital city of France"
# inputs = tokenizer(prompt, return_tensors="pt")
# outputs = model.generate(**inputs, max_length=1000)
# generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)

# print(generated_text)

# =======================================================================

# Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
# what is the capital city of France?
# The capital city of France is Paris.
# What is the capital city of the United States?
# The capital city of the United States is Washington, D.C.
# What is the capital city of the United Kingdom?
# The capital city of the United Kingdom is London.
# What is the capital city of the United States?
# The capital city of the United States is Washington, D.C.
# What is the capital city of the United States?

In [ ]:
# print(prompt)
# what is the capital city of France

In [ ]:
# print(inputs)
# {'input_ids': tensor([[10919,   318,   262,  3139,  1748,   286,  4881]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1]])}

In [ ]:
# print(inputs[0])
# Encoding(num_tokens=7, attributes=[ids, type_ids, tokens, offsets, attention_mask, special_tokens_mask, overflowing])

In [ ]:
# print(outputs)

# tensor([[10919,   318,   262,  3139,  1748,   286,  4881,    30,   198,   198,
#            464,  3139,  1748,   286,  4881,   318,  6342,    13,   198,   198,
#           2061,   318,   262,  3139,  1748,   286,   262,  1578,  1829,    30,
#            198,   198,   464,  3139,  1748,   286,   262,  1578,  1829,   318,
#            464,  3139,  1748,   286,   262,  1578,  1829,   318,  2669,    11,
#            360,    13,    34,    13,   198,   198,  2061,   318,   262,  3139]])

In [ ]:
# print(outputs[0])

# tensor([10919,   318,   262,  3139,  1748,   286,  4881,    30,   198,   198,
#           464,  3139,  1748,   286,  4881,   318,  6342,    13,   198,   198,
#          2061,   318,   262,  3139,  1748,   286,   262,  1578,  1829,    30,
#           198,   198,   464,  3139,  1748,   286,   262,  1578,  1829,   318,
#           464,  3139,  1748,   286,   262,  1578,  1829,   318,  2669,    11,
#           360,    13,    34,    13,   198,   198,  2061,   318,   262,  3139])

In [ ]:
# print(outputs[0][0])
# tensor(10919)

In [ ]:
# len(outputs[0])
# 1
# len(outputs[0])
# 1000

In [ ]:
# for i in range(len(outputs[0])):
#     generated_text_2 = tokenizer.decode(outputs[0][i])
#     print(generated_text_2, end='')

# what is the capital city of France?
# The capital city of France is Paris.
# What is the capital city of the United States?
# The capital city of the United States is Washington, D.C.
# What is the capital

In [ ]:
# for i in range(len(outputs[0])):
#     generated_text_2 = tokenizer.decode(outputs[0][i],skip_special_tokens=True)
#     print(generated_text_2, end='')

# what is the capital city of France?
# The capital city of France is Paris.
# What is the capital city of the United States?
# The capital city of the United States is Washington, D.C.
# What is the capital